# Site settings
title: HFGudeArt | Hans F. Gude Fine Art & Illustration
description: "Fine art and illustration. Official Cal (UC Berkeley) Licensed Artist, authorized to affix the University's logos to his images of the UC Berkeley campus and Cal Athletics. Subjects include landscapes, still lifes, portraits, figures, athletics. Preferred mediums include oil paint, pen & ink, gouache, watercolor, charc"
keywords: "gudeart, Gude Art, Hans Gude, Hans F. Gude, Hans Gude Art"

# The base hostname & protocol for your site.
# url: "https://www.your-domain.com"

# The subpath of your site, e.g. /blog
# baseurl: ""

# Default social media image
image: /assets/images/og_image.jpg

# Build settings
markdown: kramdown
permalink: pretty
